### ISSUE TITLE
Single Module Full Screen

### ISSUE THREAD

**Issue by shwaydogg** [climateclock/cclock#7]
Mode to show only one module at a time. Deadline full screen, then first lifeline full screen, second lifeline full screen.

**Comment by shwaydogg** [comment]
Example Design from Gan: 

<img width="488" alt="Screen Shot 2022-10-13 at 12 27 09 PM (2)" src="https://user-images.githubusercontent.com/1434147/214202360-20e1b745-12f8-437c-9370-9ca47016d8a5.png">

**Comment by zestyping** [comment]
Excluding API file changes: 3 points
Including a round of design feedback and iteration: 5 points
